version: "3.7"

services:
  # app:
  #   container_name: app
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: env/local.env
  #   ports:
  #     - 8787:8787

  redis_stack:
    image: redis/redis-stack:latest 
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    external: false
