version: "3.7"

services:
  # app:
  #   container_name: app
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: env/local.env
  #   ports:
  #     - 8787:8787

  # redis:
  #     # image: redislabs/redismod:preview
  #     image: redis/redis-stack:latest
  #     restart: always
  #     ports:
  #       - '6379:6379'
  #     # command: redis-server --save 20 1 --loglevel warning --protected-mode no
  #     volumes:
  #       - redis_data:/data

  # redis:
  #     image: redislabs/redismod
  #     restart: always
  #     ports:
  #       - '6379:6379'
  #     command: redis-server --save 20 1 --loglevel warning --requirepass strale --protected-mode no
  #     volumes:
  #       - redis_data:/data

  redis_stack:
    image: redis/redis-stack:latest 
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    external: false

# docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
# docker run -d --name redis-stack -v /tennis_redis_data/:/data -p 6379:6379 -p 8001:8001 redis/redis-stack:latest 
