// Stable, language-neutral error codes. The app translates by code
// (errors.<CODE> in the i18n files), so never reuse a code for a new meaning.
export const ErrorCode = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  CONFLICT: "CONFLICT",
  INTERNAL: "INTERNAL",
  SLOT_TAKEN: "SLOT_TAKEN",
  OUTSIDE_OPENING_HOURS: "OUTSIDE_OPENING_HOURS",
  COURT_CLOSED: "COURT_CLOSED",
  BOOKING_IN_PAST: "BOOKING_IN_PAST",
  CANCEL_TOO_LATE: "CANCEL_TOO_LATE",
  REQUEST_FULL: "REQUEST_FULL",
  ALREADY_JOINED: "ALREADY_JOINED",
  NOT_JOINED: "NOT_JOINED",
  MATCH_NOT_PENDING: "MATCH_NOT_PENDING",
  HANDOVER_PENDING: "HANDOVER_PENDING",
  RATE_LIMITED: "RATE_LIMITED",
  TOKEN_INVALID: "TOKEN_INVALID",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
