version: "3.7"

services:
  # app:
  #   container_name: app
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env.local
  #   ports:
  #     - 4005:4005

  redis:
      image: redislabs/redismod:preview
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass strale

# docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
